# Generated by Django 4.2.2 on 2023-06-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital_city', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('official_language', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
    ]
